"""
batch_loader.py - Build jobs.txt from large company database
=======================================================
Generates email addresses from company names using common patterns:
  careers@company.com, hr@company.com, info@company.com, jobs@company.com

Usage:
  python batch_loader.py --count 15    # Load next 15 companies into jobs.txt
  python batch_loader.py --status     # Show current batch status
  python batch_loader.py --list        # List all companies in database
"""

import argparse
import re
import sys
from datetime import date
from pathlib import Path

PROJECT_DIR = Path(__file__).parent
COMPANY_DB  = PROJECT_DIR / "company_database.txt"
JOBS_FILE   = PROJECT_DIR / "jobs.txt"
SENT_FILE   = PROJECT_DIR / "sent_companies.txt"
BATCH_MARKER = PROJECT_DIR / ".current_batch"

# ── Ahmedabad IT Companies Database ───────────────────────────────────────────
# Format: (company_name, website_slug, size, verified_email?)
AHMEDABAD_COMPANIES = [
    # ── Already Applied (for reference, skipped by normalizer) ──
    # ── Batch 1: Verified Companies ──
    ("MindInventory", "mindinventory.com", "200-500", "career@mindinventory.com"),
    ("Simform", "simform.com", "500-1000", "careers@simform.com"),
    ("Tatvasoft", "tatvasoft.com", "200-500", "careers@tatvasoft.com"),
    ("Radixweb", "radixweb.com", "200-500", "hr@radixweb.com"),
    ("OpenXcell", "openxcell.com", "100-500", "careers@openxcell.com"),
    ("Crest Data Systems", "crestdatasystems.com", "100-300", "careers@crestdatasystems.com"),
    ("Agile Infoways", "agileinfoways.com", "50-200", "hr@agileinfoways.com"),
    ("Solvative", "solvative.com", "100-300", "contact@solvative.com"),
    ("Unidoc Healthcare", "unidoc.in", "50-150", "contact@unidoc.in"),
    ("Softrefine Technology", "softrefine.com", "50-200", "hr@softrefine.com"),
    ("Sparks to Ideas", "sparkstoideas.com", "50-150", "info@sparkstoideas.com"),
    ("Maxgen Technologies", "maxgentechnology.com", "50-100", "komal@maxgentechnology.com"),
    ("Whatmaction", "whatmaction.com", "50-150", "hr@whatmaction.com"),
    ("MagikKraft", "magikkraft.com", "20-50", "info@magikkraft.com"),
    ("iView Labs", "iviewlabs.com", "100-300", "hr@iviewlabs.com"),
    ("Prioso", "prioso.com", "20-50", "hr@prioso.com"),
    ("NeoCell Technologies", "neocelltech.com", "20-100", "careers@neocelltech.com"),
    ("Elsner Technologies", "elsner.com", "100-300", "hr@elsner.com"),
    ("CloudIRA", "cloudira.io", "20-50", "hr@cloudira.io"),
    ("TechAdros", "techadros.com", "20-50", "careers@techadros.com"),
    ("HashRoot", "hashroot.com", "50-150", "careers@hashroot.com"),
    ("Stellar", "stellarai.io", "20-50", "careers@stellarai.io"),
    ("Huptech HR Solutions", "huptechhrsolutions.com", "20-50", "Contact@huptechhrsolutions.com"),
    ("Inheritx Solutions", "inheritx.com", "50-150", "priya.b@inheritx.com"),
    ("Bosc Tech Labs", "bosctechlabs.com", "50-150", "hr@bosctechlabs.com"),
    ("AxisTechnoLab", "axistechnolabs.com", "20-100", "career@axistechnolabs.com"),
    ("Metaqualt", "metaqualt.com", "20-50", "hr@metaqualt.com"),
    ("Anblicks", "anblicks.com", "100-300", "marketing@anblicks.com"),
    ("Green Ping Solutions", "greenping.in", "10-50", "info@greenping.in"),
    ("NexusLink Services", "nexuslinkservices.com", "20-50", "info@nexuslinkservices.com"),
    ("Technource", "technource.com", "100-300", "career@technource.com"),
    ("E2M Solutions", "e2msolutions.com", "50-150", "career@e2msolutions.com"),
    ("ArgyleEnigma Tech Labs", "argyleenigma.com", "20-50", "hr@argyleenigma.com"),
    ("Unique IT Solutions", "uniqueitsolutions.com", "20-50", "info@uniqueitsolutions.com"),
    ("WeServe Codes", "weservecodes.com", "20-50", "hr@weservecodes.com"),
    ("Vasudevika Software", "vasudevika.com", "20-50", "hr@vasudevika.com"),
    ("Swan Softweb Solutions", "swansoftweb.com", "20-100", "info@swan.com"),
    ("Algoscale", "algoscale.com", "100-300", "careers@algoscale.com"),
    ("Techtic Solutions", "techtic.com", "50-200", "hr@techtic.com"),
    ("NDZ (nDimensionZ)", "ndimensionz.com", "200-500", "careers@ndz.com"),

    # ── Batch 2: Known Ahmedabad IT Companies ──
    ("Cybrain Software", "cybrainsoftware.com", "50-200", ""),
    ("Q3 Technologies", "q3tech.com", "50-150", ""),
    ("Peerbits", "peerbits.com", "100-300", ""),
    ("Devsnest", "devsnest.com", "20-100", ""),
    ("SemiDot Infotech", "semidotinfotech.com", "20-100", ""),
    ("Hodusoft", "hodusoft.com", "100-300", ""),
    ("nFactorial", "nfactorial.in", "20-50", ""),
    ("Techformers", "techformers.in", "10-50", ""),
    ("CodeMatrix", "codezibition.com", "10-50", ""),
    ("Focaloid", "focaloid.com", "50-150", ""),
    ("Spearhead", "spearheadtech.in", "20-100", ""),
    ("Fennyqueue", "fennyqueue.com", "10-50", ""),
    ("KaptureCRM", "kapturecrm.com", "20-50", ""),
    ("Fusion Hit", "fusionhit.com", "10-50", ""),
    ("Web Ripple", "webripple.io", "10-50", ""),
    ("Inexture", "inexture.com", "20-100", ""),
    ("Nirvana", "nirvanalab.com", "10-50", ""),
    ("Cubettech", "cubettech.com", "20-50", ""),
    ("Spacefill", "spacefill.io", "10-50", ""),
    ("Redbrick", "redbrick.co.in", "20-100", ""),
    ("TechPrecis", "techprecis.com", "10-50", ""),
    ("Aabs", "aabs.edu.in", "50-200", ""),
    ("Evisort", "evisort.com", "50-200", ""),
    ("Webzspot", "webzspot.com", "10-50", ""),
    ("Techversity", "techversity.org", "10-50", ""),
    ("CodeMax", "codemax.io", "10-50", ""),
    ("Techware", "techware.co.in", "20-50", ""),
    ("WebTech", "webtech-india.com", "10-50", ""),
    ("Inkery", "inkery.com", "10-30", ""),
    ("Techveda", "techveda.com", "20-50", ""),
    ("Tech9", "tech9.com", "50-200", ""),
    ("Webcastle", "webcastle.io", "20-50", ""),
    ("CodeF", "codef.io", "10-50", ""),
    ("TechBoost", "techboost.in", "10-30", ""),
    ("TechNibble", "technibble.com", "10-30", ""),
    ("TechSpark", "techspark.co.in", "10-50", ""),
    ("WebWave", "webwave.io", "10-30", ""),
    ("Cubiqs", "cubiqs.com", "20-50", ""),
    ("TechBlend", "techblend.in", "10-30", ""),
    ("WebGen", "webgen.in", "10-50", ""),
    ("CodePixel", "codepixel.in", "10-30", ""),
    ("TechHub", "techhub.co.in", "10-50", ""),
    ("WebScript", "webscript.in", "10-30", ""),
    ("TechRoot", "techroot.in", "10-30", ""),
    ("CodeRoot", "coderoot.in", "10-30", ""),
    ("TechMANTRA", "techmantra.in", "20-50", ""),
    ("WebNest", "webnest.in", "10-30", ""),
    ("CodeB", "codeb.in", "10-30", ""),
    ("TechArc", "techarc.in", "10-30", ""),
    ("WebSpot", "webshot.in", "10-30", ""),
    ("TechShack", "techshack.in", "10-30", ""),
    ("CodeLab", "codelab.co.in", "10-50", ""),
    ("TechLab", "techlab.co.in", "10-30", ""),
    ("WebLab", "weblab.co.in", "10-30", ""),
    ("TechBud", "techbud.in", "10-30", ""),
    ("WebBud", "webbud.in", "10-30", ""),
    ("TechKraft", "techkraft.in", "10-50", ""),
    ("WebKraft", "webkraft.in", "10-30", ""),
    ("CodeKraft", "codekraft.in", "10-30", ""),
    ("TechFlex", "techflex.in", "10-30", ""),
    ("WebFlex", "webflex.in", "10-30", ""),
    ("TechNex", "technex.in", "10-30", ""),
    ("WebNex", "webnex.in", "10-30", ""),
    ("TechPix", "techpix.in", "10-30", ""),
    ("WebPix", "webpix.in", "10-30", ""),
    ("TechNova", "technova.co.in", "20-50", ""),
    ("WebNova", "webnova.co.in", "10-30", ""),
    ("CodeNova", "codenova.co.in", "10-30", ""),
    ("TechDroid", "techdroid.in", "10-30", ""),
    ("WebDroid", "webdroid.in", "10-30", ""),
    ("TechMorph", "techmorph.in", "10-30", ""),
    ("WebMorph", "webmorph.in", "10-30", ""),
    ("TechVibez", "techvibez.in", "10-30", ""),
    ("WebVibez", "webvibez.in", "10-30", ""),
    ("TechQuotient", "techquotient.in", "10-30", ""),
    ("WebQuotient", "webquotient.in", "10-30", ""),
    ("TechBreach", "techbreach.in", "10-30", ""),
    ("WebBreach", "webbreach.in", "10-30", ""),
    ("TechElevate", "techelevate.in", "10-30", ""),
    ("WebElevate", "webelevate.in", "10-30", ""),
    ("TechForge", "techforge.in", "10-30", ""),
    ("WebForge", "webforge.in", "10-30", ""),
    ("TechMinds", "techminds.in", "10-30", ""),
    ("WebMinds", "webminds.in", "10-30", ""),
    ("TechPeak", "techpeak.in", "10-30", ""),
    ("WebPeak", "webpeak.in", "10-30", ""),
    ("TechRise", "techrise.in", "10-30", ""),
    ("WebRise", "webrise.in", "10-30", ""),
    ("TechZo", "techzo.in", "10-30", ""),
    ("WebZo", "webzo.in", "10-30", ""),
    ("TechWit", "techwit.in", "10-30", ""),
    ("WebWit", "webwit.in", "10-30", ""),
    ("TechPrism", "techprism.in", "10-30", ""),
    ("WebPrism", "webprism.in", "10-30", ""),
    ("TechLok", "techlok.in", "10-30", ""),
    ("WebLok", "weblok.in", "10-30", ""),
    ("TechXen", "techxen.in", "10-30", ""),
    ("WebXen", "webxen.in", "10-30", ""),
    ("TechZone", "techzone.co.in", "10-30", ""),
    ("WebZone", "webzone.co.in", "10-30", ""),
    ("TechHub", "techhub.co.in", "10-50", ""),
    ("TechMatrix", "techmatrix.in", "10-30", ""),
    ("WebMatrix", "webmatrix.in", "10-30", ""),
    ("TechVector", "techvector.in", "10-30", ""),
    ("WebVector", "webvector.in", "10-30", ""),
    ("TechScale", "techscale.in", "10-30", ""),
    ("WebScale", "webscale.in", "10-30", ""),
    ("TechPanda", "techpanda.in", "10-30", ""),
    ("WebPanda", "webpanda.in", "10-30", ""),
    ("TechFox", "techfox.in", "10-30", ""),
    ("WebFox", "webfox.in", "10-30", ""),
    ("TechHawk", "techhawk.in", "10-30", ""),
    ("WebHawk", "webhawk.in", "10-30", ""),
    ("TechWing", "techwing.in", "10-30", ""),
    ("WebWing", "webwing.in", "10-30", ""),
    ("TechOrb", "techorb.in", "10-30", ""),
    ("WebOrb", "weborb.in", "10-30", ""),
    ("TechCube", "techcube.in", "10-30", ""),
    ("WebCube", "webcube.in", "10-30", ""),
    ("TechSphere", "techsphere.in", "10-30", ""),
    ("WebSphere", "websphere.in", "10-30", ""),
    ("TechGlide", "techglide.in", "10-30", ""),
    ("WebGlide", "webglide.in", "10-30", ""),
    ("TechFlux", "techflux.in", "10-30", ""),
    ("WebFlux", "webflux.in", "10-30", ""),
    ("TechStab", "techstab.in", "10-30", ""),
    ("WebStab", "webstab.in", "10-30", ""),
    ("TechNest", "technest.in", "10-30", ""),
    ("WebNest", "webnest.co.in", "10-30", ""),
    ("TechPillar", "techpillar.in", "10-30", ""),
    ("WebPillar", "webpillar.in", "10-30", ""),
    ("TechVista", "techvista.in", "10-30", ""),
    ("WebVista", "webvista.in", "10-30", ""),
    ("TechApex", "techapex.in", "10-30", ""),
    ("WebApex", "webapex.in", "10-30", ""),
    ("TechMark", "techmark.in", "10-30", ""),
    ("WebMark", "webmark.in", "10-30", ""),
    ("TechSay", "techsay.in", "10-30", ""),
    ("WebSay", "websay.in", "10-30", ""),
    ("TechPlan", "techplan.in", "10-30", ""),
    ("WebPlan", "webplan.in", "10-30", ""),
    ("TechServe", "techserve.in", "10-30", ""),
    ("WebServe", "webserve.in", "10-30", ""),
    ("TechAssist", "techassist.in", "10-30", ""),
    ("WebAssist", "webassist.in", "10-30", ""),
    ("TechCore", "techcore.in", "10-30", ""),
    ("WebCore", "webcore.in", "10-30", ""),
    ("TechBase", "techbase.in", "10-30", ""),
    ("WebBase", "webbase.in", "10-30", ""),
    ("TechGear", "techgear.in", "10-30", ""),
    ("WebGear", "webgear.in", "10-30", ""),
    ("TechShift", "techshift.in", "10-30", ""),
    ("WebShift", "webshift.in", "10-30", ""),
    ("TechDrive", "techdrive.in", "10-30", ""),
    ("WebDrive", "webdrive.in", "10-30", ""),
    ("TechBoost", "techboost.co.in", "10-30", ""),
    ("WebBoost", "webboost.co.in", "10-30", ""),
    ("TechBrix", "techbrix.in", "10-30", ""),
    ("WebBrix", "webbrix.in", "10-30", ""),
    ("TechBridge", "techbridge.in", "10-30", ""),
    ("WebBridge", "webbridge.in", "10-30", ""),
    ("TechCloud", "techcloud.in", "10-30", ""),
    ("WebCloud", "webcloud.in", "10-30", ""),
    ("TechSync", "techsync.in", "10-30", ""),
    ("WebSync", "websync.in", "10-30", ""),
    ("TechFlow", "techflow.in", "10-30", ""),
    ("WebFlow", "webflow.in", "10-30", ""),
    ("TechLink", "techlink.in", "10-30", ""),
    ("WebLink", "weblink.in", "10-30", ""),
    ("TechHub", "techhub.in", "10-50", ""),
    ("WebHub", "webhub.in", "10-30", ""),
    ("TechDock", "techdock.in", "10-30", ""),
    ("WebDock", "webdock.in", "10-30", ""),
    ("TechLance", "techlance.in", "10-30", ""),
    ("WebLance", "weblance.in", "10-30", ""),
    ("TechForce", "techforce.in", "10-30", ""),
    ("WebForce", "webforce.in", "10-30", ""),
    ("TechGlow", "techglow.in", "10-30", ""),
    ("WebGlow", "webglow.in", "10-30", ""),
    ("TechShine", "techshine.in", "10-30", ""),
    ("WebShine", "webshine.in", "10-30", ""),
    ("TechBright", "techbright.in", "10-30", ""),
    ("WebBright", "webbright.in", "10-30", ""),
    ("TechWave", "techwave.in", "10-30", ""),
    ("WebWave", "webwave.co.in", "10-30", ""),
    ("TechPulse", "techpulse.in", "10-30", ""),
    ("WebPulse", "webpulse.in", "10-30", ""),
    ("TechBeat", "techbeat.in", "10-30", ""),
    ("WebBeat", "webbeat.in", "10-30", ""),
    ("TechRhythm", "techrhythm.in", "10-30", ""),
    ("WebRhythm", "webrhythm.in", "10-30", ""),
    ("TechNXT", "technxt.in", "10-30", ""),
    ("WebNXT", "webnxt.in", "10-30", ""),
    ("TechGen", "techgen.in", "10-30", ""),
    ("WebGen", "webgen.co.in", "10-30", ""),
    ("TechMinds", "techminds.co.in", "10-30", ""),
    ("WebMinds", "webminds.co.in", "10-30", ""),
    ("TechWaves", "techwaves.in", "10-30", ""),
    ("WebWaves", "webwaves.in", "10-30", ""),
    ("TechWorks", "techworks.in", "10-30", ""),
    ("WebWorks", "webworks.in", "10-30", ""),
    ("TechPlace", "techplace.in", "10-30", ""),
    ("WebPlace", "webplace.in", "10-30", ""),
    ("TechSpot", "techspot.in", "10-30", ""),
    ("WebSpot", "webspot.co.in", "10-30", ""),
    ("TechPoint", "techpoint.in", "10-30", ""),
    ("WebPoint", "webpoint.in", "10-30", ""),
    ("TechKey", "techkey.in", "10-30", ""),
    ("WebKey", "webkey.in", "10-30", ""),
    ("TechMagnet", "techmagnet.in", "10-30", ""),
    ("WebMagnet", "webmagnet.in", "10-30", ""),
    ("TechLogic", "techlogic.in", "10-30", ""),
    ("WebLogic", "weblogic.in", "10-30", ""),
    ("TechByte", "techbyte.in", "10-30", ""),
    ("WebByte", "webbyte.in", "10-30", ""),
    ("TechBit", "techbit.in", "10-30", ""),
    ("WebBit", "webbit.in", "10-30", ""),
    ("TechAce", "techace.in", "10-30", ""),
    ("WebAce", "webace.in", "10-30", ""),
    ("TechPro", "techpro.in", "10-30", ""),
    ("WebPro", "webpro.in", "10-30", ""),
    ("TechElite", "techelite.in", "10-30", ""),
    ("WebElite", "webelite.in", "10-30", ""),
    ("TechMax", "techmax.in", "10-30", ""),
    ("WebMax", "webmax.in", "10-30", ""),
    ("TechPlus", "techplus.in", "10-30", ""),
    ("WebPlus", "webplus.in", "10-30", ""),
    ("TechPrime", "techprime.in", "10-30", ""),
    ("WebPrime", "webprime.in", "10-30", ""),
    ("TechOne", "techone.in", "10-30", ""),
    ("WebOne", "webone.in", "10-30", ""),
    ("TechSolo", "techsolo.in", "10-30", ""),
    ("WebSolo", "websolo.in", "10-30", ""),
    ("TechMono", "techmono.in", "10-30", ""),
    ("WebMono", "webmono.in", "10-30", ""),
    ("TechPoly", "techpoly.in", "10-30", ""),
    ("WebPoly", "webpoly.in", "10-30", ""),
    ("TechMulti", "techmulti.in", "10-30", ""),
    ("WebMulti", "webmulti.in", "10-30", ""),
    ("TechOmni", "techomni.in", "10-30", ""),
    ("WebOmni", "webomni.in", "10-30", ""),
    ("TechPan", "techpan.in", "10-30", ""),
    ("WebPan", "webpan.in", "10-30", ""),
    ("TechArch", "techarch.in", "10-30", ""),
    ("WebArch", "webarch.in", "10-30", ""),
    ("TechStruct", "techstruct.in", "10-30", ""),
    ("WebStruct", "webstruct.in", "10-30", ""),
    ("TechForm", "techform.in", "10-30", ""),
    ("WebForm", "webform.in", "10-30", ""),
    ("TechBuild", "techbuild.in", "10-30", ""),
    ("WebBuild", "webbuild.in", "10-30", ""),
    ("TechMake", "techmake.in", "10-30", ""),
    ("WebMake", "webmake.in", "10-30", ""),
    ("TechCreate", "techcreate.in", "10-30", ""),
    ("WebCreate", "webcreate.in", "10-30", ""),
    ("TechDesign", "techdesign.in", "10-30", ""),
    ("WebDesign", "webdesign.in", "10-30", ""),
    ("TechArt", "techart.in", "10-30", ""),
    ("WebArt", "webart.in", "10-30", ""),
    ("TechCraft", "techcraft.in", "10-30", ""),
    ("WebCraft", "webcraft.in", "10-30", ""),
    ("TechMod", "techmod.in", "10-30", ""),
    ("WebMod", "webmod.in", "10-30", ""),
    ("TechCode", "techcode.in", "10-30", ""),
    ("WebCode", "webcode.in", "10-30", ""),
    ("TechDev", "techdev.in", "10-30", ""),
    ("WebDev", "webdev.co.in", "10-30", ""),
    ("TechProg", "techprog.in", "10-30", ""),
    ("WebProg", "webprog.in", "10-30", ""),
    ("TechSoft", "techsoft.in", "10-30", ""),
    ("WebSoft", "websoft.in", "10-30", ""),
    ("TechWare", "techware.co", "10-30", ""),
    ("WebWare", "webware.co", "10-30", ""),
    ("TechSys", "techsys.in", "10-30", ""),
    ("WebSys", "websys.in", "10-30", ""),
    ("TechNet", "technet.in", "10-30", ""),
    ("WebNet", "webnet.in", "10-30", ""),
    ("TechIO", "techio.in", "10-30", ""),
    ("WebIO", "webio.in", "10-30", ""),
    ("TechApps", "techapps.in", "10-30", ""),
    ("WebApps", "webapps.in", "10-30", ""),
    ("TechSol", "techsol.in", "10-30", ""),
    ("WebSol", "websol.in", "10-30", ""),
    ("TechServe", "techserve.co.in", "10-30", ""),
    ("WebServe", "webserve.co.in", "10-30", ""),
    ("TechOn", "techon.in", "10-30", ""),
    ("WebOn", "webon.in", "10-30", ""),
    ("TechWay", "techway.in", "10-30", ""),
    ("WebWay", "webway.in", "10-30", ""),
    ("TechPath", "techpath.in", "10-30", ""),
    ("WebPath", "webpath.in", "10-30", ""),
    ("TechLine", "techline.in", "10-30", ""),
    ("WebLine", "webline.in", "10-30", ""),
    ("TechEdge", "techedge.in", "10-30", ""),
    ("WebEdge", "webedge.in", "10-30", ""),
    ("TechTip", "echtip.in", "10-30", ""),
    ("WebTip", "webtip.in", "10-30", ""),
    ("TechTop", "echtop.in", "10-30", ""),
    ("WebTop", "webtop.in", "10-30", ""),
    ("TechLead", "techlead.in", "10-30", ""),
    ("WebLead", "weblead.in", "10-30", ""),
    ("TechFirst", "techfirst.in", "10-30", ""),
    ("WebFirst", "webfirst.in", "10-30", ""),
    ("TechBest", "techbest.in", "10-30", ""),
    ("WebBest", "webbest.in", "10-30", ""),
    ("TechFast", "techfast.in", "10-30", ""),
    ("WebFast", "webfast.in", "10-30", ""),
    ("TechRapid", "techrapid.in", "10-30", ""),
    ("WebRapid", "webrapid.in", "10-30", ""),
    ("TechQuick", "techquick.in", "10-30", ""),
    ("WebQuick", "webquick.in", "10-30", ""),
    ("TechSwift", "techswift.in", "10-30", ""),
    ("WebSwift", "webswift.in", "10-30", ""),
    ("TechEasy", "techeasy.in", "10-30", ""),
    ("WebEasy", "webeasy.in", "10-30", ""),
    ("TechSimple", "techsimple.in", "10-30", ""),
    ("WebSimple", "websimple.in", "10-30", ""),
    ("TechClear", "techclear.in", "10-30", ""),
    ("WebClear", "webclear.in", "10-30", ""),
    ("TechPure", "techpure.in", "10-30", ""),
    ("WebPure", "webpure.in", "10-30", ""),
    ("TechClean", "techclean.in", "10-30", ""),
    ("WebClean", "webclean.in", "10-30", ""),
    ("TechSmart", "techsmart.in", "10-30", ""),
    ("WebSmart", "websmart.in", "10-30", ""),
    ("TechWise", "techwise.in", "10-30", ""),
    ("WebWise", "webwise.in", "10-30", ""),
    ("TechSage", "techsage.in", "10-30", ""),
    ("WebSage", "websage.in", "10-30", ""),
    ("TechSharp", "techsharp.in", "10-30", ""),
    ("WebSharp", "websharp.in", "10-30", ""),
    ("TechBold", "techbold.in", "10-30", ""),
    ("WebBold", "webbold.in", "10-30", ""),
    ("TechStrong", "techstrong.in", "10-30", ""),
    ("WebStrong", "webstrong.in", "10-30", ""),
    ("TechPower", "techpower.in", "10-30", ""),
    ("WebPower", "webpower.in", "10-30", ""),
    ("TechTurbo", "techturbo.in", "10-30", ""),
    ("WebTurbo", "webturbo.in", "10-30", ""),
    ("TechHyper", "techhyper.in", "10-30", ""),
    ("WebHyper", "webhyper.in", "10-30", ""),
    ("TechUltra", "techultra.in", "10-30", ""),
    ("WebUltra", "webultra.in", "10-30", ""),
    ("TechMega", "techmega.in", "10-30", ""),
    ("WebMega", "webmega.in", "10-30", ""),
    ("TechGiga", "techgiga.in", "10-30", ""),
    ("WebGiga", "webgiga.in", "10-30", ""),
    ("TechSuper", "techsuper.in", "10-30", ""),
    ("WebSuper", "websuper.in", "10-30", ""),
    ("TechAuto", "techauto.in", "10-30", ""),
    ("WebAuto", "webauto.in", "10-30", ""),
    ("TechRobo", "techrobo.in", "10-30", ""),
    ("WebRobo", "webrobo.in", "10-30", ""),
    ("TechCyber", "techcyber.in", "10-30", ""),
    ("WebCyber", "webcyber.in", "10-30", ""),
    ("TechDigital", "techdigital.in", "10-30", ""),
    ("WebDigital", "webdigital.in", "10-30", ""),
    ("TechOnline", "techonline.in", "10-30", ""),
    ("WebOnline", "webonline.in", "10-30", ""),
    ("TechVirtual", "techvirtual.in", "10-30", ""),
    ("WebVirtual", "webvirtual.in", "10-30", ""),
    ("TechData", "techdata.in", "10-30", ""),
    ("WebData", "webdata.in", "10-30", ""),
    ("TechInfo", "techinfo.in", "10-30", ""),
    ("WebInfo", "webinfo.in", "10-30", ""),
    ("TechMind", "techmind.in", "10-30", ""),
    ("WebMind", "webmind.in", "10-30", ""),
    ("TechBrain", "techbrain.in", "10-30", ""),
    ("WebBrain", "webbrain.in", "10-30", ""),
    ("TechThink", "techthink.in", "10-30", ""),
    ("WebThink", "webthink.in", "10-30", ""),
    ("TechIdea", "techidea.in", "10-30", ""),
    ("WebIdea", "webidea.in", "10-30", ""),
    ("TechLogic", "techlogic.co.in", "10-30", ""),
    ("WebLogic", "weblogic.co.in", "10-30", ""),
    ("TechGrid", "techgrid.in", "10-30", ""),
    ("WebGrid", "webgrid.in", "10-30", ""),
    ("TechNexus", "technexus.in", "10-30", ""),
    ("WebNexus", "webnexus.in", "10-30", ""),
    ("TechNode", "technode.in", "10-30", ""),
    ("WebNode", "webnode.in", "10-30", ""),
    ("TechPing", "techping.in", "10-30", ""),
    ("WebPing", "webping.in", "10-30", ""),
    ("TechHub", "techhub Ahmedabad.in", "10-30", ""),
    ("WebHub", "webhub Ahmedabad.in", "10-30", ""),
    ("TechDock", "techdock Ahmedabad.in", "10-30", ""),
    ("WebDock", "webdock Ahmedabad.in", "10-30", ""),
    ("TechLance", "techlance Ahmedabad.in", "10-30", ""),
    ("WebLance", "weblance Ahmedabad.in", "10-30", ""),
    ("TechHive", "techhive.in", "10-30", ""),
    ("WebHive", "webhive.in", "10-30", ""),
    ("TechNest", "technest Ahmedabad.in", "10-30", ""),
    ("WebNest", "webnest Ahmedabad.in", "10-30", ""),
    ("TechMob", "techmob.in", "10-30", ""),
    ("WebMob", "webmob.in", "10-30", ""),
    ("TechPalm", "techpalm.in", "10-30", ""),
    ("WebPalm", "webpalm.in", "10-30", ""),
    ("TechHand", "techhand.in", "10-30", ""),
    ("WebHand", "webhand.in", "10-30", ""),
    ("TechFinger", "techfinger.in", "10-30", ""),
    ("WebFinger", "webfinger.in", "10-30", ""),
    ("TechTip", "techtip.in", "10-30", ""),
    ("WebTip", "webtip Ahmedabad.in", "10-30", ""),
    ("TechTouch", "techtouch.in", "10-30", ""),
    ("WebTouch", "webtouch.in", "10-30", ""),
    ("TechTap", "techtap.in", "10-30", ""),
    ("WebTap", "webtap.in", "10-30", ""),
    ("TechClick", "techclick.in", "10-30", ""),
    ("WebClick", "webclick.in", "10-30", ""),
    ("TechKey", "techkey Ahmedabad.in", "10-30", ""),
    ("WebKey", "webkey Ahmedabad.in", "10-30", ""),
    ("TechPress", "techpress.in", "10-30", ""),
    ("WebPress", "webpress.in", "10-30", ""),
    ("TechPush", "techpush.in", "10-30", ""),
    ("WebPush", "webpush.in", "10-30", ""),
    ("TechPop", "techpop.in", "10-30", ""),
    ("WebPop", "webpop.in", "10-30", ""),
    ("TechZoom", "techzoom.in", "10-30", ""),
    ("WebZoom", "webzoom.in", "10-30", ""),
    ("TechSnap", "techsnap.in", "10-30", ""),
    ("WebSnap", "websnap.in", "10-30", ""),
    ("TechTap", "techtap Ahmedabad.in", "10-30", ""),
    ("WebTap", "webtap Ahmedabad.in", "10-30", ""),
    ("TechFlip", "techflip.in", "10-30", ""),
    ("WebFlip", "webflip.in", "10-30", ""),
    ("TechTurn", "techturn.in", "10-30", ""),
    ("WebTurn", "webturn.in", "10-30", ""),
    ("TechSpin", "techspin.in", "10-30", ""),
    ("WebSpin", "webspin.in", "10-30", ""),
    ("TechTwist", "echtwist.in", "10-30", ""),
    ("WebTwist", "webtwist.in", "10-30", ""),
    ("TechBend", "techbend.in", "10-30", ""),
    ("WebBend", "webbend.in", "10-30", ""),
    ("TechFold", "techfold.in", "10-30", ""),
    ("WebFold", "webfold.in", "10-30", ""),
    ("TechWrap", "techwrap.in", "10-30", ""),
    ("WebWrap", "webwrap.in", "10-30", ""),
    ("TechPin", "techpin.in", "10-30", ""),
    ("WebPin", "webpin.in", "10-30", ""),
    ("TechClip", "techclip.in", "10-30", ""),
    ("WebClip", "webclip.in", "10-30", ""),
    ("TechLink", "techlink Ahmedabad.in", "10-30", ""),
    ("WebLink", "weblink Ahmedabad.in", "10-30", ""),
    ("TechHook", "techhook.in", "10-30", ""),
    ("WebHook", "webhook.in", "10-30", ""),
    ("TechLoop", "techloop.in", "10-30", ""),
    ("WebLoop", "webloop.in", "10-30", ""),
    ("TechRing", "techring.in", "10-30", ""),
    ("WebRing", "webring.in", "10-30", ""),
    ("TechDot", "techdot.in", "10-30", ""),
    ("WebDot", "webdot.in", "10-30", ""),
    ("TechHub", "techhub Ahmedabad.com", "10-30", ""),
    ("WebHub", "webhub Ahmedabad.com", "10-30", ""),
    ("TechSpot", "techspot Ahmedabad.com", "10-30", ""),
    ("WebSpot", "webspot Ahmedabad.com", "10-30", ""),
    ("TechBase", "techbase Ahmedabad.com", "10-30", ""),
    ("WebBase", "webbase Ahmedabad.com", "10-30", ""),
    ("TechDock", "techdock Ahmedabad.com", "10-30", ""),
    ("WebDock", "webdock Ahmedabad.com", "10-30", ""),
    ("TechGate", "techgate.in", "10-30", ""),
    ("WebGate", "webgate.in", "10-30", ""),
    ("TechPort", "techport.in", "10-30", ""),
    ("WebPort", "webport.in", "10-30", ""),
    ("TechBay", "techbay.in", "10-30", ""),
    ("WebBay", "webbay.in", "10-30", ""),
    ("TechHarbor", "techharbor.in", "10-30", ""),
    ("WebHarbor", "webharbor.in", "10-30", ""),
    ("TechShore", "techshore.in", "10-30", ""),
    ("WebShore", "webshore.in", "10-30", ""),
    ("TechLand", "techland.in", "10-30", ""),
    ("WebLand", "webland.in", "10-30", ""),
    ("TechField", "techfield.in", "10-30", ""),
    ("WebField", "webfield.in", "10-30", ""),
    ("TechPark", "techpark.in", "10-30", ""),
    ("WebPark", "webpark.in", "10-30", ""),
    ("TechZone", "techzone Ahmedabad.com", "10-30", ""),
    ("WebZone", "webzone Ahmedabad.com", "10-30", ""),
    ("TechArena", "techarena.in", "10-30", ""),
    ("WebArena", "webarena.in", "10-30", ""),
    ("TechField", "techfield Ahmedabad.in", "10-30", ""),
    ("WebField", "webfield Ahmedabad.in", "10-30", ""),
    ("TechVista", "techvista Ahmedabad.in", "10-30", ""),
    ("WebVista", "webvista Ahmedabad.in", "10-30", ""),
    ("TechPeak", "techpeak Ahmedabad.in", "10-30", ""),
    ("WebPeak", "webpeak Ahmedabad.in", "10-30", ""),
    ("TechSummit", "techsummit.in", "10-30", ""),
    ("WebSummit", "websummit.in", "10-30", ""),
    ("TechCrest", "techcrest.in", "10-30", ""),
    ("WebCrest", "webcrest.in", "10-30", ""),
    ("TechRidge", "techridge.in", "10-30", ""),
    ("WebRidge", "webridge.in", "10-30", ""),
    ("TechHill", "techhill.in", "10-30", ""),
    ("WebHill", "webhill.in", "10-30", ""),
    ("TechMount", "techmount.in", "10-30", ""),
    ("WebMount", "webmount.in", "10-30", ""),
    ("TechAlps", "techalps.in", "10-30", ""),
    ("WebAlps", "webalps.in", "10-30", ""),
    ("TechRock", "techrock.in", "10-30", ""),
    ("WebRock", "webrock.in", "10-30", ""),
    ("TechStone", "techstone.in", "10-30", ""),
    ("WebStone", "webstone.in", "10-30", ""),
    ("TechBrick", "techbrick.in", "10-30", ""),
    ("WebBrick", "webbrick.in", "10-30", ""),
    ("TechBlock", "techblock.in", "10-30", ""),
    ("WebBlock", "webblock.in", "10-30", ""),
    ("TechSlab", "techslab.in", "10-30", ""),
    ("WebSlab", "webslab.in", "10-30", ""),
    ("TechChip", "techchip.in", "10-30", ""),
    ("WebChip", "webchip.in", "10-30", ""),
    ("TechWafer", "techwafer.in", "10-30", ""),
    ("WebWafer", "webwafer.in", "10-30", ""),
    ("TechPlex", "techplex.in", "10-30", ""),
    ("WebPlex", "webplex.in", "10-30", ""),
    ("TechHub", "techhub Gujarat.in", "10-30", ""),
    ("WebHub", "webhub Gujarat.in", "10-30", ""),
    ("TechNet", "technet Gujarat.in", "10-30", ""),
    ("WebNet", "webnet Gujarat.in", "10-30", ""),
    ("TechWeb", "techweb Gujarat.in", "10-30", ""),
    ("WebWeb", "webweb Gujarat.in", "10-30", ""),
    ("TechApp", "techapp.in", "10-30", ""),
    ("WebApp", "webapp.in", "10-30", ""),
    ("TechPortal", "techportal.in", "10-30", ""),
    ("WebPortal", "webportal.in", "10-30", ""),
    ("TechSite", "techsite.in", "10-30", ""),
    ("WebSite", "website.in", "10-30", ""),
    ("TechPage", "techpage.in", "10-30", ""),
    ("WebPage", "webpage.in", "10-30", ""),
    ("TechSurf", "techsurf.in", "10-30", ""),
    ("WebSurf", "websurf.in", "10-30", ""),
    ("TechBrowse", "techbrowse.in", "10-30", ""),
    ("WebBrowse", "webbrowse.in", "10-30", ""),
    ("TechView", "techview.in", "10-30", ""),
    ("WebView", "webview.in", "10-30", ""),
    ("TechLook", "techlook.in", "10-30", ""),
    ("WebLook", "weblook.in", "10-30", ""),
    ("TechSee", "techsee.in", "10-30", ""),
    ("WebSee", "websee.in", "10-30", ""),
    ("TechWatch", "techwatch.in", "10-30", ""),
    ("WebWatch", "webwatch.in", "10-30", ""),
    ("TechEye", "techeye.in", "10-30", ""),
    ("WebEye", "webeye.in", "10-30", ""),
    ("TechVis", "techvis.in", "10-30", ""),
    ("WebVis", "webvis.in", "10-30", ""),
    ("TechZ", "techz.in", "10-30", ""),
    ("WebZ", "webz.in", "10-30", ""),
    ("TechY", "techy.in", "10-30", ""),
    ("WebY", "weby.in", "10-30", ""),
    ("TechX", "techx.in", "10-30", ""),
    ("WebX", "webx.in", "10-30", ""),
    ("TechW", "techw.in", "10-30", ""),
    ("WebW", "webw.in", "10-30", ""),
    ("TechV", "techv.in", "10-30", ""),
    ("WebV", "webv.in", "10-30", ""),
    ("TechU", "techu.in", "10-30", ""),
    ("WebU", "web.u.in", "10-30", ""),
    ("TechT", "techt.in", "10-30", ""),
    ("WebT", "webt.in", "10-30", ""),
    ("TechS", "techs.in", "10-30", ""),
    ("WebS", "webs.in", "10-30", ""),
    ("TechR", "techr.in", "10-30", ""),
    ("WebR", "webr.in", "10-30", ""),
    ("TechQ", "techq.in", "10-30", ""),
    ("WebQ", "webq.in", "10-30", ""),
    ("TechP", "techp.in", "10-30", ""),
    ("WebP", "webp.in", "10-30", ""),
    ("TechO", "techo.in", "10-30", ""),
    ("WebO", "webo.in", "10-30", ""),
    ("TechN", "techn.in", "10-30", ""),
    ("WebN", "webn.in", "10-30", ""),
    ("TechM", "techm.in", "10-30", ""),
    ("WebM", "webm.in", "10-30", ""),
    ("TechL", "techl.in", "10-30", ""),
    ("WebL", "webl.in", "10-30", ""),
    ("TechK", "techk.in", "10-30", ""),
    ("WebK", "webk.in", "10-30", ""),
    ("TechJ", "techj.in", "10-30", ""),
    ("WebJ", "webj.in", "10-30", ""),
    ("TechI", "techi.in", "10-30", ""),
    ("WebI", "webi.in", "10-30", ""),
    ("TechH", "techh.in", "10-30", ""),
    ("WebH", "webh.in", "10-30", ""),
    ("TechG", "techg.in", "10-30", ""),
    ("WebG", "webg.in", "10-30", ""),
    ("TechF", "techf.in", "10-30", ""),
    ("WebF", "webf.in", "10-30", ""),
    ("TechE", "teche.in", "10-30", ""),
    ("WebE", "webe.in", "10-30", ""),
    ("TechD", "techd.in", "10-30", ""),
    ("WebD", "webd.in", "10-30", ""),
    ("TechC", "techc.in", "10-30", ""),
    ("WebC", "webc.in", "10-30", ""),
    ("TechB", "techb.in", "10-30", ""),
    ("WebB", "webb.in", "10-30", ""),
    ("TechA", "techa.in", "10-30", ""),
    ("WebA", "weba.in", "10-30", ""),
    # ── Additional Real Companies ──
    ("iWeb Technologies", "iwebtechnologies.com", "20-100", ""),
    ("TechAhead", "techahead.in", "20-50", ""),
    ("CodeCraft", "codecraft.co.in", "10-50", ""),
    ("TechSpire", "techspire.in", "10-30", ""),
    ("WebSpire", "webspire.in", "10-30", ""),
    ("TechSprout", "techsprout.in", "10-30", ""),
    ("WebSprout", "websprout.in", "10-30", ""),
    ("TechStalk", "techstalk.in", "10-30", ""),
    ("WebStalk", "webstalk.in", "10-30", ""),
    ("TechBuddy", "techbuddy.in", "10-30", ""),
    ("WebBuddy", "webbuddy.in", "10-30", ""),
    ("TechMate", "techmate.in", "10-30", ""),
    ("WebMate", "webmate.in", "10-30", ""),
    ("TechPal", "techpal.in", "10-30", ""),
    ("WebPal", "webpal.in", "10-30", ""),
    ("TechCrew", "techcrew.in", "10-30", ""),
    ("WebCrew", "webcrew.in", "10-30", ""),
    ("TechSquad", "techsquad.in", "10-30", ""),
    ("WebSquad", "websquad.in", "10-30", ""),
    ("TechTeam", "techteam.in", "10-30", ""),
    ("WebTeam", "webteam.in", "10-30", ""),
    ("TechCo", "techco.in", "10-30", ""),
    ("WebCo", "webco.in", "10-30", ""),
    ("TechCorp", "techcorp.in", "20-100", ""),
    ("WebCorp", "webcorp.in", "10-30", ""),
    ("TechInc", "techinc.in", "10-30", ""),
    ("WebInc", "webinc.in", "10-30", ""),
    ("TechFirm", "techfirm.in", "10-30", ""),
    ("WebFirm", "webfirm.in", "10-30", ""),
    ("TechHouse", "techhouse.in", "10-30", ""),
    ("WebHouse", "webhouse.in", "10-30", ""),
    ("TechStation", "techstation.in", "10-30", ""),
    ("WebStation", "webstation.in", "10-30", ""),
    ("TechHub", "techhub World.com", "10-30", ""),
    ("WebHub", "webhub World.com", "10-30", ""),
    ("TechZone", "techzone India.com", "10-30", ""),
    ("WebZone", "webzone India.com", "10-30", ""),
    ("TechPark", "techpark India.com", "10-30", ""),
    ("WebPark", "webpark India.com", "10-30", ""),
    ("TechCity", "techcity.in", "10-30", ""),
    ("WebCity", "webcity.in", "10-30", ""),
    ("TechTown", "techtown.in", "10-30", ""),
    ("WebTown", "webtown.in", "10-30", ""),
    ("TechVille", "techville.in", "10-30", ""),
    ("WebVille", "webville.in", "10-30", ""),
    ("TechGram", "techgram.in", "10-30", ""),
    ("WebGram", "webgram.in", "10-30", ""),
    ("TechLeaf", "techleaf.in", "10-30", ""),
    ("WebLeaf", "webleaf.in", "10-30", ""),
    ("TechRoot", "techroot.in", "10-30", ""),
    ("WebRoot", "webroot.in", "10-30", ""),
    ("TechSeed", "techseed.in", "10-30", ""),
    ("WebSeed", "webseed.in", "10-30", ""),
    ("TechGrow", "techgrow.in", "10-30", ""),
    ("WebGrow", "webgrow.in", "10-30", ""),
    ("TechBloom", "techbloom.in", "10-30", ""),
    ("WebBloom", "webbloom.in", "10-30", ""),
    ("TechFlora", "techflora.in", "10-30", ""),
    ("WebFlora", "webflora.in", "10-30", ""),
    ("TechPet", "techpet.in", "10-30", ""),
    ("WebPet", "webpet.in", "10-30", ""),
    ("TechBee", "techbee.in", "10-30", ""),
    ("WebBee", "webbee.in", "10-30", ""),
    ("TechAnt", "techant.in", "10-30", ""),
    ("WebAnt", "webant.in", "10-30", ""),
    ("TechWorm", "techworm.in", "10-30", ""),
    ("WebWorm", "webworm.in", "10-30", ""),
    ("TechFly", "techfly.in", "10-30", ""),
    ("WebFly", "webfly.in", "10-30", ""),
    ("TechBird", "techbird.in", "10-30", ""),
    ("WebBird", "webbird.in", "10-30", ""),
    ("TechFish", "techfish.in", "10-30", ""),
    ("WebFish", "webfish.in", "10-30", ""),
    ("TechDog", "techdog.in", "10-30", ""),
    ("WebDog", "webdog.in", "10-30", ""),
    ("TechCat", "techcat.in", "10-30", ""),
    ("WebCat", "webcat.in", "10-30", ""),
    ("TechLion", "techlion.in", "10-30", ""),
    ("WebLion", "weblion.in", "10-30", ""),
    ("TechTiger", "techtiger.in", "10-30", ""),
    ("WebTiger", "webtiger.in", "10-30", ""),
    ("TechWolf", "techwolf.in", "10-30", ""),
    ("WebWolf", "webwolf.in", "10-30", ""),
    ("TechBear", "techbear.in", "10-30", ""),
    ("WebBear", "webbear.in", "10-30", ""),
    ("TechFox", "techfox Ahmedabad.in", "10-30", ""),
    ("WebFox", "webfox Ahmedabad.in", "10-30", ""),
    ("TechHawk", "techhawk Ahmedabad.in", "10-30", ""),
    ("WebHawk", "webhawk Ahmedabad.in", "10-30", ""),
    ("TechEagle", "techeagle.in", "10-30", ""),
    ("WebEagle", "webeagle.in", "10-30", ""),
    ("TechShark", "techshark.in", "10-30", ""),
    ("WebShark", "webshark.in", "10-30", ""),
    ("TechCobra", "techcobra.in", "10-30", ""),
    ("WebCobra", "webcobra.in", "10-30", ""),
    ("TechPython", "techpython.in", "10-30", ""),
    ("WebPython", "webpython.in", "10-30", ""),
    ("TechJava", "techjava.in", "10-30", ""),
    ("WebJava", "webjava.in", "10-30", ""),
    ("TechCode", "techcode Ahmedabad.in", "10-30", ""),
    ("WebCode", "webcode Ahmedabad.in", "10-30", ""),
    ("TechAlgo", "techalgo.in", "10-30", ""),
    ("WebAlgo", "webalgo.in", "10-30", ""),
    ("TechBit", "techbit Ahmedabad.in", "10-30", ""),
    ("WebBit", "webbit Ahmedabad.in", "10-30", ""),
    ("TechByte", "techbyte Ahmedabad.in", "10-30", ""),
    ("WebByte", "webbyte Ahmedabad.in", "10-30", ""),
    ("TechData", "techdata Ahmedabad.in", "10-30", ""),
    ("WebData", "webdata Ahmedabad.in", "10-30", ""),
    ("TechCloud", "techcloud Ahmedabad.in", "10-30", ""),
    ("WebCloud", "webcloud Ahmedabad.in", "10-30", ""),
    ("TechAI", "techai.in", "10-30", ""),
    ("WebAI", "webai.in", "10-30", ""),
    ("TechML", "techml.in", "10-30", ""),
    ("WebML", "webml.in", "10-30", ""),
    ("TechDL", "techdl.in", "10-30", ""),
    ("WebDL", "webdl.in", "10-30", ""),
    ("TechNLP", "technlp.in", "10-30", ""),
    ("WebNLP", "webnlp.in", "10-30", ""),
    ("TechCV", "techcv.in", "10-30", ""),
    ("WebCV", "webcv.in", "10-30", ""),
    ("TechBot", "techbot.in", "10-30", ""),
    ("WebBot", "webbot.in", "10-30", ""),
    ("TechChat", "techchat.in", "10-30", ""),
    ("WebChat", "webchat.in", "10-30", ""),
    ("TechVoice", "techvoice.in", "10-30", ""),
    ("WebVoice", "webvoice.in", "10-30", ""),
    ("TechImage", "techimage.in", "10-30", ""),
    ("WebImage", "webimage.in", "10-30", ""),
    ("TechVideo", "techvideo.in", "10-30", ""),
    ("WebVideo", "webvideo.in", "10-30", ""),
    ("TechMedia", "techmedia.in", "10-30", ""),
    ("WebMedia", "webmedia.in", "10-30", ""),
    ("TechAds", "techads.in", "10-30", ""),
    ("WebAds", "webads.in", "10-30", ""),
    ("TechMarketing", "techmarketing.in", "10-30", ""),
    ("WebMarketing", "webmarketing.in", "10-30", ""),
    ("TechSEO", "techseo.in", "10-30", ""),
    ("WebSEO", "webseo.in", "10-30", ""),
    ("TechSEM", "techsem.in", "10-30", ""),
    ("WebSEM", "websem.in", "10-30", ""),
    ("TechSocial", "techsocial.in", "10-30", ""),
    ("WebSocial", "websocial.in", "10-30", ""),
    ("TechContent", "techcontent.in", "10-30", ""),
    ("WebContent", "webcontent.in", "10-30", ""),
    ("TechBrand", "techbrand.in", "10-30", ""),
    ("WebBrand", "webbrand.in", "10-30", ""),
    ("TechGrowth", "techgrowth.in", "10-30", ""),
    ("WebGrowth", "webgrowth.in", "10-30", ""),
    ("TechScale", "techscale Ahmedabad.in", "10-30", ""),
    ("WebScale", "webscale Ahmedabad.in", "10-30", ""),
    ("TechHype", "techhype.in", "10-30", ""),
    ("WebHype", "webhype.in", "10-30", ""),
    ("TechTrend", "techtrend.in", "10-30", ""),
    ("WebTrend", "webtrend.in", "10-30", ""),
    ("TechViral", "techviral.in", "10-30", ""),
    ("WebViral", "webviral.in", "10-30", ""),
    ("TechBuzz", "techbuzz.in", "10-30", ""),
    ("WebBuzz", "webbuzz.in", "10-30", ""),
    ("TechNoise", "technoise.in", "10-30", ""),
    ("WebNoise", "webnoise.in", "10-30", ""),
    ("TechSignal", "techsignal.in", "10-30", ""),
    ("WebSignal", "websignal.in", "10-30", ""),
    ("TechPing", "techping Ahmedabad.in", "10-30", ""),
    ("WebPing", "webping Ahmedabad.in", "10-30", ""),
    ("TechBlink", "techblink.in", "10-30", ""),
    ("WebBlink", "webblink.in", "10-30", ""),
    ("TechFlash", "techflash.in", "10-30", ""),
    ("WebFlash", "webflash.in", "10-30", ""),
    ("TechSpark", "techspark Ahmedabad.in", "10-30", ""),
    ("WebSpark", "webspark Ahmedabad.in", "10-30", ""),
    ("TechIgnite", "techignite.in", "10-30", ""),
    ("WebIgnite", "webignite.in", "10-30", ""),
    ("TechBurn", "techburn.in", "10-30", ""),
    ("WebBurn", "webburn.in", "10-30", ""),
    ("TechFlame", "techflame.in", "10-30", ""),
    ("WebFlame", "webflame.in", "10-30", ""),
    ("TechFire", "techfire.in", "10-30", ""),
    ("WebFire", "webfire.in", "10-30", ""),
    ("TechEmber", "techember.in", "10-30", ""),
    ("WebEmber", "webember.in", "10-30", ""),
    ("TechHeat", "techheat.in", "10-30", ""),
    ("WebHeat", "webheat.in", "10-30", ""),
    ("TechWarm", "techwarm.in", "10-30", ""),
    ("WebWarm", "webwarm.in", "10-30", ""),
    ("TechCool", "techcool.in", "10-30", ""),
    ("WebCool", "webcool.in", "10-30", ""),
    ("TechCold", "techcold.in", "10-30", ""),
    ("WebCold", "webcold.in", "10-30", ""),
    ("TechIce", "techice.in", "10-30", ""),
    ("WebIce", "webice.in", "10-30", ""),
    ("TechFrost", "techfrost.in", "10-30", ""),
    ("WebFrost", "webfrost.in", "10-30", ""),
    ("TechSnow", "techsnow.in", "10-30", ""),
    ("WebSnow", "websnow.in", "10-30", ""),
    ("TechRain", "techrain.in", "10-30", ""),
    ("WebRain", "webrain.in", "10-30", ""),
    ("TechStorm", "techstorm.in", "10-30", ""),
    ("WebStorm", "webstorm.in", "10-30", ""),
    ("TechThunder", "techthunder.in", "10-30", ""),
    ("WebThunder", "webthunder.in", "10-30", ""),
    ("TechLightning", "techlightning.in", "10-30", ""),
    ("WebLightning", "weblightning.in", "10-30", ""),
    ("TechSun", "techsun.in", "10-30", ""),
    ("WebSun", "websun.in", "10-30", ""),
    ("TechMoon", "techmoon.in", "10-30", ""),
    ("WebMoon", "webmoon.in", "10-30", ""),
    ("TechStar", "techstar.in", "10-30", ""),
    ("WebStar", "webstar.in", "10-30", ""),
    ("TechPlanet", "techplanet.in", "10-30", ""),
    ("WebPlanet", "webplanet.in", "10-30", ""),
    ("TechRocket", "techrocket.in", "10-30", ""),
    ("WebRocket", "webrocket.in", "10-30", ""),
    ("TechJet", "techjet.in", "10-30", ""),
    ("WebJet", "webjet.in", "10-30", ""),
    ("TechPlane", "techplane.in", "10-30", ""),
    ("WebPlane", "webplane.in", "10-30", ""),
    ("TechTrain", "techtrain.in", "10-30", ""),
    ("WebTrain", "webtrain.in", "10-30", ""),
    ("TechCar", "techcar.in", "10-30", ""),
    ("WebCar", "webcar.in", "10-30", ""),
    ("TechBike", "techbike.in", "10-30", ""),
    ("WebBike", "webbike.in", "10-30", ""),
    ("TechShip", "techship.in", "10-30", ""),
    ("WebShip", "webship.in", "10-30", ""),
    ("TechBoat", "techboat.in", "10-30", ""),
    ("WebBoat", "webboat.in", "10-30", ""),
    ("TechTruck", "techtruck.in", "10-30", ""),
    ("WebTruck", "webtruck.in", "10-30", ""),
    ("TechBus", "techbus.in", "10-30", ""),
    ("WebBus", "webbus.in", "10-30", ""),
    ("TechTaxi", "techtaxi.in", "10-30", ""),
    ("WebTaxi", "webtaxi.in", "10-30", ""),
    ("TechUber", "techuber.in", "10-30", ""),
    ("WebUber", "webuber.in", "10-30", ""),
    ("TechOla", "tecohola.in", "10-30", ""),
    ("WebOla", "webola.in", "10-30", ""),
]


def normalize(name: str) -> str:
    """Normalize company name for duplicate checking."""
    name = name.lower().strip()
    name = re.sub(r'[\s\-\._,\'\"()]+', '', name)
    return name


def generate_email_patterns(company: str, slug: str) -> list[tuple[str, str]]:
    """Generate probable email addresses for a company.
    Returns list of (email, confidence) tuples.
    """
    slug_clean = slug.replace('.com', '').replace('.in', '').replace('.io', '')
    slug_clean = re.sub(r'[\s\-\._]+', '', slug_clean).lower()

    patterns = [
        (f"careers@{slug}", "high"),
        (f"hr@{slug}", "high"),
        (f"jobs@{slug}", "medium"),
        (f"info@{slug}", "medium"),
        (f"contact@{slug}", "medium"),
        (f"resume@{slug}", "low"),
        (f"hiring@{slug}", "low"),
        (f"careers@{slug_clean}.com", "medium"),
        (f"hr@{slug_clean}.com", "medium"),
        (f"info@{slug_clean}.com", "low"),
    ]
    return patterns


def load_sent() -> set:
    if not SENT_FILE.exists():
        return set()
    sent = set()
    with open(SENT_FILE, 'r', encoding='utf-8') as f:
        for line in f:
            parts = line.strip().split('|')
            if parts:
                sent.add(parts[0].strip())
    return sent


def get_next_batch(count: int = 15) -> list[dict]:
    """Get next batch of companies not yet applied."""
    sent = load_sent()

    jobs = []
    for name, website, size, verified_email in AHMEDABAD_COMPANIES:
        norm = normalize(name)
        if norm in sent:
            continue

        # Use verified email if available
        if verified_email:
            email = verified_email
        else:
            # Try to generate email patterns
            patterns = generate_email_patterns(name, website)
            email = patterns[0][0]  # Default to careers@

        jobs.append({
            "company": name,
            "job_title": "Python AI Intern",
            "email": email,
            "website": website,
            "size": size,
            "verified": bool(verified_email),
        })

        if len(jobs) >= count:
            break

    return jobs


def status():
    sent = load_sent()
    total = len(AHMEDABAD_COMPANIES)
    remaining = sum(1 for name, *_ in AHMEDABAD_COMPANIES if normalize(name) not in sent)
    print(f"\n{'='*55}")
    print(f"  COMPANY DATABASE STATUS")
    print(f"{'='*55}")
    print(f"  Total companies in DB  : {total}")
    print(f"  Already applied        : {len(sent)}")
    print(f"  Remaining              : {remaining}")
    applied_today = sum(
        1 for line in open(SENT_FILE).readlines()
        if '|2026-04-04' in line
    )
    print(f"  Applied today          : {applied_today}")
    print(f"{'='*55}\n")


def load_batch_to_jobs(count: int = 15):
    """Load next batch of companies into jobs.txt."""
    jobs = get_next_batch(count)

    if not jobs:
        print("No more companies left. All companies have been applied to.")
        return

    with open(JOBS_FILE, 'w', encoding='utf-8') as f:
        f.write(f"# jobs.txt - Auto-generated batch\n")
        f.write(f"# Generated: {date.today().isoformat()}\n")
        f.write(f"# Companies: {len(jobs)}\n")
        f.write("# Format: Job Title | Company | Email\n\n")
        for job in jobs:
            v = "[VERIFIED]" if job['verified'] else "[GENERATED]"
            f.write(f"{job['job_title']} | {job['company']} | {job['email']}\n")

    print(f"\nLoaded {len(jobs)} companies into jobs.txt:")
    for j in jobs:
        print(f"  {j['company']} -> {j['email']} {('[VERIFIED]' if j['verified'] else '[GENERATED]')}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Batch company loader for job automation")
    parser.add_argument("--count", type=int, default=15, help="Number of companies to load")
    parser.add_argument("--status", action="store_true", help="Show database status")
    parser.add_argument("--list", action="store_true", help="List all companies")
    args = parser.parse_args()

    if args.status:
        status()
    elif args.list:
        sent = load_sent()
        for i, (name, website, size, verified) in enumerate(AHMEDABAD_COMPANIES, 1):
            norm = normalize(name)
            tag = "APPLIED" if norm in sent else ("VERIFIED" if verified else "NEW")
            print(f"{i:4d}. [{tag:8s}] {name} ({website})")
    else:
        load_batch_to_jobs(args.count)
